version: 2
formats:
  - htmlzip
  - pdf
conda:
  environment: docs/docs-env.yml
build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false
