import itertools

import numpy as np

from mbuild.compound import Compound
from mbuild.atom import Atom
from mbuild.bond import Bond

def load_mol2(filename):
    """
    """
    component = Compound()

    with open(filename, 'r') as mol2_file:
        data = dict((key, list(grp)) for key, grp in itertools.groupby(mol2_file, _parse_mol2_sections))

    for atom in data['@<TRIPOS>ATOM\n'][1:]:
        _, _, x, y, z, kind, _, _, _ = atom.split()
        position = np.array([float(x), float(y), float(z)])
        component.add(Atom(kind, position))
    """
    for bond in data['@<TRIPOS>BOND\n'][1:]:
        _, atom1_idx, atom_2idx, _ = bond.split()
        atom1 = 'blah'
        atom2 = 'blah2'
        component.add(Bond(atom1, atom2))
    """
    return component

def write_mol2(component, filename='mbuild.mol2'):
    """
    """
    n_atoms = len(list(component.atoms()))
    n_bonds = len(component.bonds)

    with open(filename, 'w') as mol2_file:
        mol2_file.write("@<TRIPOS>MOLECULE\n")
        mol2_file.write("Generated by mBuild\n")
        mol2_file.write("{0} {1} 0 0 0\n".format(n_atoms, n_bonds))
        mol2_file.write("SMALL\n")
        mol2_file.write("NO_CHARGES\n")
        mol2_file.write("\n")

        mol2_file.write("@<TRIPOS>ATOM\n")
        for atom_idx, atom in enumerate(component.atoms()):
            atom.idx = atom_idx + 1
            x, y, z = atom.pos
            mol2_file.write("{0} {1} {2:8.3f} {3:8.3f} {4:8.3f} {5}\n".format(
                    atom.idx, atom.kind[0], x, y, z, atom.kind))

        if n_bonds:
            mol2_file.write("@<TRIPOS>BONDS\n")
            for bond_idx, bond in enumerate(component.bonds):
                mol2_file.write("{0} {1} {2} 1\n".format(
                        bond_idx + 1, bond.atom1.idx, bond.atom2.idx))

def _parse_mol2_sections(x):
    """
    """
    if x.startswith('@<TRIPOS>'):
        _parse_mol2_sections.key = x
    return _parse_mol2_sections.key

if __name__ == "__main__":
    import pdb
    component = load_mol2('ethanol.mol2')
    write_mol2(component, 'ethanol_out.mol2')



