package:
  name: mbuild-dev
  version: !!str 0.6.0.dev0

requirements:
  build:
    - python
    - cython
    - numpy
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - mdtraj
    - packmol
    - nglview
    - oset
    - parmed
    - jupyter
    - nbformat
    - ipykernel
    - ipyext

test:
  requires:
    - pytest
  commands:
    - py.test -v --pyargs mbuild
    - cd {{SRC_DIR}}
    - cd mbuild/examples
    - py.test test_examples.py -v

about:
  home: http://imodels.github.io/mbuild
  license: MIT
  summary: A hierarchical, component based molecule builder.
