package:
  name: mbuild
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)}}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - scipy
    - packmol 1.0.0
    - nglview >=0.6
    - oset
    - parmed
    - mdtraj 1.9.1

test:
  requires:
    - pytest >=3.0
    - jupyter
    - nbformat
    - ipykernel
    - ipyext
    - pytest-ignore-flaky
    - foyer

  source_files:
    - mbuild/examples/*

  commands:
    - set LNAME=mosdef
    - pytest --ignore-flaky -v --pyargs mbuild

about:
  home: http://mosdef-hub.github.io/mbuild
  license: MIT
  summary: A hierarchical, component based molecule builder.
