package:
  name: mbuild
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../../

build:
  noarch: python
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)}}
  preserve_egg_dir: True
  script_env:
    - CONDA_PY
  script: activate
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - protobuf

  run:
    - python
    - numpy
    - scipy
    - packmol >=1!18.013
    - oset
    - parmed
    - protobuf
    - mdtraj
    - setuptools
    - openbabel >=3.0.0

test:
  requires:
    - pytest >=3.0
    - foyer
    - networkx

  commands:
    - set LNAME=mosdef
    - activate
    - pytest -v --pyargs mbuild

about:
  home: http://mosdef-hub.github.io/mbuild
  license: MIT
  summary: A hierarchical, component based molecule builder.
