package:
  name: mbuild
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)}}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - scipy
    - packmol 1.0.0
    - nglview >=0.6 # [not win]
    - oset
    - parmed
    - mdtraj

test:
  requires:
    - pytest >=3.0
    - jupyter
    - nbformat
    - ipykernel
    - ipyext

  source_files:
    - mbuild/examples/*

  commands:
    - py.test -v --pyargs mbuild
    - cd mbuild/examples
    - py.test test_examples.py -v

about:
  home: http://mosdef-hub.github.io/mbuild
  license: MIT
  summary: A hierarchical, component based molecule builder.
