!#/bin/bash

PROJECT_DIR=`pwd`
echo "Project dir is: " $PROJECT_DIR
TEMP_DIR=/tmp/doc`date +%s`
mkdir $TEMP_DIR
echo "Temp dir is: " $TEMP_DIR

pushd $TEMP_DIR

echo "Cloning github repo"
git clone https://$GITHUB_TOKEN@github.com/iModels/mbuild.git

cd mbuild/
echo "Switching to gh-pages branch"
git checkout gh-pages

echo "Copying autogenerated docs to gh-pages branch"
cp -r $PROJECT_DIR .

echo "Commiting and pushing back to github"
git add -A docs
git commit -m "updating autogenerated docs"
git push
