__author__ = 'CTK'


def write_mol2(compound, filename, show_ports=False):
    """Output a Trajectory as a TRIPOS mol2 file.

    Parameters
    ----------
    filename : str
        Path of the output file.

    """

    atoms = compound.atom_list_by_kind(excludeG=not show_ports)
    bonds = compound.bonds

    with open(filename, 'w') as mol2_file:
        mol2_file.write("@<TRIPOS>MOLECULE\n")
        mol2_file.write("Generated by mBuild\n")
        mol2_file.write("{0} {1} 0 0 0\n".format(len(atoms), len(bonds)))
        mol2_file.write("SMALL\n")
        mol2_file.write("NO_CHARGES\n")
        mol2_file.write("\n")

        mol2_file.write("@<TRIPOS>ATOM\n")
        atom_mapping = dict()
        for n, atom in enumerate(atoms):
            x, y, z = atom.pos * 10.0  # Nanometers to angstroms.
            mol2_file.write("{0:d} {1:s} {2:8.4f} {3:8.4f} {4:8.4f} {5} {6:d} {7:s} {8:8.4f}\n".format(
                n + 1, atom.kind, x, y, z, atom.kind, 1, 'RES', 0.0))
            atom_mapping[atom] = n + 1

        if len(bonds) > 0:
            mol2_file.write("@<TRIPOS>BOND\n")
            for bond_n, bond in enumerate(bonds):
                atom1 = atom_mapping[bond.atom1]
                atom2 = atom_mapping[bond.atom2]
                mol2_file.write("{0} {1} {2} 1\n".format(bond_n + 1, atom1, atom2))
        mol2_file.write("<@TRIPOS>\n")
